### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by JustinRvt** [EmixMaxime/Front-end-boilerplate-with-webpack#1]
Salut, 

Ton lien dans le README.md s'appelle Front-end-boilerplate-with-webpack mais redirige sur Front-end-boilerplate-with-gulp.
Est-ce que tu vas continuer de travailler sur webpack ou gulp du coup ? 
Je n'ai pas tout saisi.

Amicalement,

Justin.

**Comment by EmixMaxime** [comment]
Salut,
Ops une erreur de ma part je voulais mettre le lien vers Gulp.
Actuellement je travail sur Gulp donc je mets à jour ce dépôt, c'est pourquoi ma config webpack n'a pour le moment qu'un commit.
Je continue de travailler avec webpack mais plus pour le moment (ça devrait revenir assez prochainement).
Désolé pour la petite erreur
